(function(b){b(function(){var e=b.support,a;a:{a=document.createElement("bootstrap");var c={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},d;for(d in c)if(void 0!==a.style[d]){a=c[d];break a}a=void 0}e.transition=a&&{end:a}})})(window.jQuery);
(function(b){var e=function(a,c){this.$element=b(a);this.options=b.extend({},b.fn.button.defaults,c)};e.prototype.setState=function(a){var c=this.$element,b=c.data(),f=c.is("input")?"val":"html";a+="Text";b.resetText||c.data("resetText",c[f]());c[f](b[a]||this.options[a]);setTimeout(function(){"loadingText"==a?c.addClass("disabled").attr("disabled","disabled"):c.removeClass("disabled").removeAttr("disabled")},0)};e.prototype.toggle=function(){var a=this.$element.closest('[data-toggle="buttons-radio"]');
a&&a.find(".active").removeClass("active");this.$element.toggleClass("active")};b.fn.button=function(a){return this.each(function(){var c=b(this),d=c.data("button"),f="object"==typeof a&&a;d||c.data("button",d=new e(this,f));"toggle"==a?d.toggle():a&&d.setState(a)})};b.fn.button.defaults={loadingText:"loading..."};b.fn.button.Constructor=e;b(document).on("click.button.data-api","[data-toggle^=button]",function(a){a=b(a.target);a.hasClass("btn")||(a=a.closest(".btn"));a.button("toggle")})})(window.jQuery);
(function(b){var e=function(a,c){this.init("tooltip",a,c)};e.prototype={constructor:e,init:function(a,c,d){this.type=a;this.$element=b(c);this.options=this.getOptions(d);this.enabled=!0;if("click"==this.options.trigger)this.$element.on("click."+this.type,this.options.selector,b.proxy(this.toggle,this));else"manual"!=this.options.trigger&&(a="hover"==this.options.trigger?"mouseenter":"focus",c="hover"==this.options.trigger?"mouseleave":"blur",this.$element.on(a+"."+this.type,this.options.selector,
b.proxy(this.enter,this)),this.$element.on(c+"."+this.type,this.options.selector,b.proxy(this.leave,this)));this.options.selector?this._options=b.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()},getOptions:function(a){a=b.extend({},b.fn[this.type].defaults,a,this.$element.data());a.delay&&"number"==typeof a.delay&&(a.delay={show:a.delay,hide:a.delay});return a},enter:function(a){var c=b(a.currentTarget)[this.type](this._options).data(this.type);if(!c.options.delay||!c.options.delay.show)return c.show();
clearTimeout(this.timeout);c.hoverState="in";this.timeout=setTimeout(function(){"in"==c.hoverState&&c.show()},c.options.delay.show)},leave:function(a){var c=b(a.currentTarget)[this.type](this._options).data(this.type);this.timeout&&clearTimeout(this.timeout);if(!c.options.delay||!c.options.delay.hide)return c.hide();c.hoverState="out";this.timeout=setTimeout(function(){"out"==c.hoverState&&c.hide()},c.options.delay.hide)},show:function(){var a,c,b,f,g,e,h;if(this.hasContent()&&this.enabled){a=this.tip();
this.setContent();this.options.width&&a.css({maxWidth:"none",width:this.options.width});this.options.animation&&a.addClass("fade");e="function"==typeof this.options.placement?this.options.placement.call(this,a[0],this.$element[0]):this.options.placement;c=/in/.test(e);a.remove().css({top:0,left:0,display:"block"}).appendTo(c?this.$element:document.body);b=this.getPosition(c);f=a[0].offsetWidth;g=a[0].offsetHeight;switch(c?e.split(" ")[1]:e){case "bottom":h={top:b.top+b.height,left:b.left+b.width/
2-f/2};break;case "top":h={top:b.top-g,left:b.left+b.width/2-f/2};break;case "left":h={top:b.top+b.height/2-g/2,left:b.left-f};break;case "right":h={top:b.top+b.height/2-g/2,left:b.left+b.width}}a.css(h).addClass(e).addClass("in");this.$element.trigger(this.type+"-shown")}},setContent:function(){var a=this.tip(),b=this.getTitle();a.find(".tooltip-inner")[this.options.html?"html":"text"](b);a.removeClass("fade in top bottom left right")},hide:function(){function a(){var a=setTimeout(function(){d.off(b.support.transition.end).remove()},
500);d.one(b.support.transition.end,function(){clearTimeout(a);d.remove();c.$element.trigger(c.type+"-hidden")})}var c=this,d=this.tip();d.removeClass("in");b.support.transition&&this.$tip.hasClass("fade")?a():(d.remove(),c.$element.trigger(c.type+"-hidden"));return this},fixTitle:function(){var a=this.$element;(a.attr("title")||"string"!=typeof a.attr("data-original-title"))&&a.attr("data-original-title",a.attr("title")||b(a.data("content")).html()||"").removeAttr("title")},hasContent:function(){return this.getTitle()},
getPosition:function(a){return b.extend({},a?{top:0,left:0}:this.$element.offset(),{width:this.$element[0].offsetWidth,height:this.$element[0].offsetHeight})},getTitle:function(){var a=this.$element,b=this.options;return a.attr("data-original-title")||("function"==typeof b.title?b.title.call(a[0]):b.title)},tip:function(){return this.$tip=this.$tip||b(this.options.template)},validate:function(){this.$element[0].parentNode||(this.hide(),this.options=this.$element=null)},enable:function(){this.enabled=
!0},disable:function(){this.enabled=!1},toggleEnabled:function(){this.enabled=!this.enabled},toggle:function(){this[this.tip().hasClass("in")?"hide":"show"]()},destroy:function(){this.hide().$element.off("."+this.type).removeData(this.type)}};b.fn.tooltip=function(a){return this.each(function(){var c=b(this),d=c.data("tooltip"),f="object"==typeof a&&a;d||c.data("tooltip",d=new e(this,f));if("string"==typeof a)d[a]()})};b.fn.tooltip.Constructor=e;b.fn.tooltip.defaults={animation:!0,placement:"top",
selector:!1,template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"><div class="tooltip-inner"></div></div>',trigger:"hover",title:"",delay:0,html:!0}})(window.jQuery);
(function(b){var e=function(a,b){this.init("popover",a,b)};e.prototype=b.extend({},b.fn.tooltip.Constructor.prototype,{constructor:e,setContent:function(){var a=this.tip(),b=this.getTitle(),d=this.getContent();a.find(".popover-title")[this.options.html?"html":"text"](b);a.find(".popover-content")[this.options.html?"html":"text"](d);a.removeClass("fade top bottom left right in")},hasContent:function(){return this.getTitle()||this.getContent()},getContent:function(){var a=this.$element,c=this.options;
return b(a.data("content")).html()||a.attr("data-content")||("function"==typeof c.content?c.content.call(a[0]):c.content)},tip:function(){this.$tip||(this.$tip=b(this.options.template));return this.$tip},destroy:function(){this.hide().$element.off("."+this.type).removeData(this.type)}});b.fn.popover=function(a){return this.each(function(){var c=b(this),d=c.data("popover"),f="object"==typeof a&&a;d||c.data("popover",d=new e(this,f));if("string"==typeof a)d[a]()})};b.fn.popover.Constructor=e;b.fn.popover.defaults=
b.extend({},b.fn.tooltip.defaults,{placement:"right",trigger:"click",content:"",template:'<div class="popover"><div class="arrow"></div><div class="popover-inner"><h3 class="popover-title"></h3><div class="popover-content"></div></div></div>'})})(window.jQuery);$(document).ready(function(){$("[rel=popover]").popover();$("[rel=tooltip]").tooltip()});
(function(b){var e=function(a,c){this.options=c;this.$element=b(a).delegate('[data-dismiss="modal"]',"click.dismiss.modal",b.proxy(this.hide,this));this.options.remote&&this.$element.find(".modal-body").load(this.options.remote)};e.prototype={constructor:e,toggle:function(){return this[this.isShown?"hide":"show"]()},show:function(){var a=this,c=b.Event("show");this.$element.trigger(c);this.isShown||c.isDefaultPrevented()||(this.isShown=!0,this.escape(),this.backdrop(function(){var c=b.support.transition&&
a.$element.is(".falling, .fade, .collapse");a.$element.parent().length||a.$element.appendTo(document.body);a.$element.show();c&&a.$element[0].offsetHeight;a.$element.addClass("in");c?a.$element.one(b.support.transition.end,function(){a.$element.trigger("shown").find("button:last-child").focus()}):a.$element.trigger("shown").find("button:last-child").focus()}))},hide:function(a){a&&a.preventDefault();a=b.Event("hide");this.$element.trigger(a);this.isShown&&!a.isDefaultPrevented()&&(this.isShown=!1,
this.escape(),b(document).off("focusin.modal"),this.$element.removeClass("in"),b.support.transition&&this.$element.is(".falling, .fade, .collapse")?this.hideWithTransition():this.hideModal())},escape:function(){var a=this;if(this.isShown&&this.options.keyboard)this.$element.on("keyup.dismiss.modal",function(b){27==b.which&&a.hide()});else this.isShown||this.$element.off("keyup.dismiss.modal")},hideWithTransition:function(){var a=this,c=setTimeout(function(){a.$element.off(b.support.transition.end);
a.hideModal()},1E3);this.$element.one(b.support.transition.end,function(){clearTimeout(c);a.hideModal()})},hideModal:function(a){this.$element.hide().trigger("hidden");this.backdrop()},removeBackdrop:function(){this.$backdrop.remove();this.$backdrop=null},backdrop:function(a){var c=this.$element.is(".falling, .fade, .collapse")?"fade":"";if(this.isShown&&this.options.backdrop){var d=b.support.transition&&c;this.$backdrop=b('<div class="modal-backdrop '+c+'" />').appendTo(document.body);this.$backdrop.click("static"==
this.options.backdrop?b.proxy(this.$element.focus,this.$element.find("button:last-child")):b.proxy(this.hide,this));d&&this.$backdrop[0].offsetWidth;this.$backdrop.addClass("in");d?this.$backdrop.one(b.support.transition.end,a):a()}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),b.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one(b.support.transition.end,b.proxy(this.removeBackdrop,this)):this.removeBackdrop()):a&&a()}};b.fn.modal=function(a){return this.each(function(){var c=
b(this),d=c.data("modal"),f=b.extend({},b.fn.modal.defaults,c.data(),"object"==typeof a&&a);d||c.data("modal",d=new e(this,f));if("string"==typeof a)d[a]();else f.show&&d.show()})};b.fn.modal.defaults={backdrop:!0,keyboard:!0,show:!0};b.fn.modal.Constructor=e;b(document).on("click.modal.data-api",'[data-toggle="modal"]',function(a){var c=b(this),d=c.attr("href"),f=b(c.attr("data-target")||d&&d.replace(/.*(?=#[^\s]+$)/,"")),d=f.data("modal")?"toggle":b.extend({remote:!/#/.test(d)&&d},f.data(),c.data());
a.preventDefault();f.modal(d).one("hide",function(){c.focus()})})})(window.jQuery);
!function(b){var e=function(a){this.element=b(a)};e.prototype={constructor:e,show:function(){var a=this.element,c=a.closest("ul:not(.dropdown-menu)"),d=a.attr("data-target"),f,g;d||(d=(d=a.attr("href"))&&d.replace(/.*(?=#[^\s]*$)/,""));a.parent("li").hasClass("active")||(f=c.find(".active:last a")[0],g=b.Event("show",{relatedTarget:f}),a.trigger(g),g.isDefaultPrevented()||(d=b(d),this.activate(a.parent("li"),c),this.activate(d,d.parent(),function(){a.trigger({type:"shown",relatedTarget:f})})))},activate:function(a,
c,d){function f(){g.removeClass("active").find("> .dropdown-menu > .active").removeClass("active");a.addClass("active");e?(a[0].offsetWidth,a.addClass("in")):a.removeClass("fade");a.parent(".dropdown-menu")&&a.closest("li.dropdown").addClass("active");d&&d()}var g=c.find("> .active"),e=d&&b.support.transition&&g.hasClass("fade");e?g.one(b.support.transition.end,f):f();g.removeClass("in")}};b.fn.tab=function(a){return this.each(function(){var c=b(this),d=c.data("tab");d||c.data("tab",d=new e(this));
if("string"==typeof a)d[a]()})};b.fn.tab.Constructor=e;b(document).on("click.tab.data-api",'[data-toggle="tab"], [data-toggle="pill"]',function(a){a.preventDefault();b(this).tab("show")})}(window.jQuery);
!function(b){function e(){b(c).each(function(){a(b(this)).removeClass("open")})}function a(a){var c=a.attr("data-target");c||(c=(c=a.attr("href"))&&/#/.test(c)&&c.replace(/.*(?=#[^\s]*$)/,""));c=b(c);c.length||(c=a.parent());return c}var c="[data-toggle=dropdown]",d=function(a){var c=b(a).on("click.dropdown.data-api",this.toggle);b("html").on("click.dropdown.data-api",function(){c.parent().removeClass("open")})};d.prototype={constructor:d,toggle:function(c){c=b(this);var d,k;if(!c.is(".disabled, :disabled"))return d=
a(c),k=d.hasClass("open"),e(),k||(d.toggleClass("open"),c.focus()),!1},keydown:function(c){var d,e,h;if(/(38|40|27)/.test(c.keyCode)&&(d=b(this),c.preventDefault(),c.stopPropagation(),!d.is(".disabled, :disabled"))){e=a(d);h=e.hasClass("open");if(!h||h&&27==c.keyCode)return d.click();d=b("[role=menu] li:not(.divider) a",e);d.length&&(e=d.index(d.filter(":focus")),38==c.keyCode&&0<e&&e--,40==c.keyCode&&e<d.length-1&&e++,~e||(e=0),d.eq(e).focus())}}};b.fn.dropdown=function(a){return this.each(function(){var c=
b(this),e=c.data("dropdown");e||c.data("dropdown",e=new d(this));"string"==typeof a&&e[a].call(c)})};b.fn.dropdown.Constructor=d;b(document).on("click.dropdown.data-api touchstart.dropdown.data-api",e).on("click.dropdown touchstart.dropdown.data-api",".dropdown form",function(a){a.stopPropagation()}).on("click.dropdown.data-api touchstart.dropdown.data-api",c,d.prototype.toggle).on("keydown.dropdown.data-api touchstart.dropdown.data-api",c+", [role=menu]",d.prototype.keydown)}(window.jQuery);